### ISSUE TITLE
Setting contribution guidelines for repository contributors

### ISSUE THREAD

**Issue by HeinKhantZaw** [rocky-linux/infrastructure#14951] opened 2020-12-19 04:45 UTC
I think there should be CONTRIBUTING.md of how people should contribute to this repo.

**Comment by nazunalika** [comment] 2020-12-19 04:51
The `README` of the `infrastructure/ansible` portion of this repo does talk about how to contribute already to the ansible portion, and what is expected. We will look into a contributors portion at the root.

**Comment by NeilHanlon** [comment] 2020-12-31 02:58
Closing, duplicate of #1

**Closed by NeilHanlon** 2020-12-31 02:58 UTC
